export const supplyCategories = [
    "Food",
    "Water",
    "Medicine",
    "First Aid",
    "Clothing",
    "Blankets",
    "Hygiene Kits",
    "Baby Supplies",
    "Sanitary Items",
    "Tents",
    "Sleeping Bags",
    "Flashlights",
    "Batteries",
    "Cooking Equipment",
    "Pet Supplies",
    "Masks",
    "Disinfectants",
    "Toiletries",
    "Cleaning Supplies",
    "Footwear",
    "Fuel",
    "Wheelchairs & Crutches",
    "Emergency Rations",
  ];
  